### ISSUE TITLE
Posts (timeline) Page

### ISSUE THREAD

**Issue by missbabelfish** [Hack-Weekly/indigo-turtle-blog#2]
- [x] Create page with empty div
- [x] Show blog posts loaded from an array of dummy blog posts.
- [x] Create popup for blog posts.
- [x] Implement delete operation for blog post.
- [x] Implement edit operation for blog post.
- [x] Create vertical navbar with the option buttons having onClick={()=> console.log("implement me")}
- [x] Implement handler for "My Post" option.
- [x] Implement handler for "Create" option.
- [x] Implement handler for "Accounts" option.
- [x] Implement handler for log out button.
- [x] Handle a state where when user is not logged in, the vertical navbar should prompt the user to sign up or sign in (instead of displaying the three options).

**Comment by OwenTruong** [comment]
Hm not sure what to mean the component exactly in React. Should I name it as PostsPage?

**Comment by OwenTruong** [comment]
Going to separate "create a type called Post with the following properties: author, date, title, content, tags" task to a new issue (as both PostPage and the create post page missbabelfish is working on requires this type urgently)
